config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  resources :friendships
  resources :images
  devise_for :users
  root 'static_pages#home'

  resources :users do
    resources :chats, only: [:index, :show, :create]
  end
  resources :messages, only:[:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  #if chat is destroyed all messages and subscriptions will also be  destroyed
  has_many :users, through: :subscriptions
  validates :identifier, presence: true, uniqueness: true,    case_sensitive: false
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file ,ImageUploader
  belongs_to :user
  has_many :image_like, -> { order "created_at DESC"}
end

app/models/image_comment.rb
class ImageComment < ActiveRecord::Base
end

app/models/image_like.rb
class ImageLike < ApplicationRecord
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :tweet, counter_cache: :likes_count
    belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    has_many :likes, dependent: :destroy
    def like_user(user_id)
        likes.find_by(user_id: user_id)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :age, presence: true
  has_many :images
  has_many :friendships
  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions

  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
      existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
    end
    existing_chat_users.uniq
  end

end

app/controllers/chats_controller.rb
require 'securerandom'

class ChatsController < ApplicationController
  before_action :require_login
  def index
    chats = current_user.chats
    @existing_chats_users = current_user.existing_chats_users
    @available_user = current_user.friendships.where(state:"approved")
  end

  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    if !@chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to user_chat_path(current_user, @chat,  :other_user => @other_user.id)
  end


  def show
    @other_user = User.find(params[:other_user])
    @chat = Chat.find_by(id: params[:id])
    @message = Message.new
  end

  private
  def find_chat(second_user)
    chats = current_user.chats
    chats.each do |chat|
      chat.subscriptions.each do |s|
        if s.user_id == second_user.id
          return chat
        end
      end
    end
    nil
  end

  def require_login
    redirect_to new_session_path unless current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/image_likes_helper.rb
module ImageLikesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/chats/index.html.erb
<div style="margin-left: 5%; margin-top: 80px">
  <div style="">
    <p style="font-size: 34px">
      Some friend are missing you!
    </p>
  </div>
  <ul>
    <% if @existing_chats_users %>
        <% @existing_chats_users.each do |other_user| %>
            <% if other_user != current_user %>
                <li style="font-size: 20px">
                  <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
                      <%= other_user.name %>
                  <% end %>
                </li>
            <% end %>
        <% end %>
    <% end %>
  </ul>
  <p style="font-size: 34px">
    Let's say hello with new friend!
  </p>
  <ul>
    <% @available_user.all.each do |other_user| %>
        <% if other_user.user_id != current_user %>
            <li style="font-size: 20px">
              <%= link_to(user_chats_path(current_user, :other_user => other_user.friend_id), method: :post) do %>
                  <%= User.find_by(id:other_user.friend_id).name %>
              <% end %>
            </li>
        <% end %>
    <% end %>
  </ul>
</div>

app/views/chats/show.html.erb
<div class="chat">
  <div class="chat-title">
    <h1><%= @other_user.name %></h1>
    <h2>Have a nice day!</h2>
    <figure class="avatar">
      <img src="https://ui-avatars.com/api/?name=<%= @other_user.name %>" />
    </figure>
  </div>
<div class="scroll">
  <% if @chat.messages.any? %>
      <div id="messages" style="font-size: 16px; color: white; margin-left: 20px;">
        <%= render partial: 'messages/message', collection: @chat.messages.order(id: :asc)%>
      </div>
  <%else%>
      <div id="messages">
      </div>
  <%end%>
</div>
<div class="message-box">
  <%= render partial: 'messages/message_form', locals: {message: @message, chat: @chat}%>
</div>
</div>

<p><%= link_to "Back to list of chats", user_chats_path(current_user.id) %></p>

<script>
    createMessageChannel();
    messageForm();
    //defaults scrolling to bottom
    $(".scroll").scrollTop($(".scroll")[0].scrollHeight);
</script>