config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  resources :friendships
  resources :images
  devise_for :users
  root 'static_pages#home'

  resources :users do
    resources :chats, only: [:index, :show, :create]
  end
  resources :messages, only:[:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  #if chat is destroyed all messages and subscriptions will also be  destroyed
  has_many :users, through: :subscriptions
  validates :identifier, presence: true, uniqueness: true,    case_sensitive: false
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file ,ImageUploader
  belongs_to :user
  has_many :image_like, -> { order "created_at DESC"}
end

app/models/image_comment.rb
class ImageComment < ActiveRecord::Base
end

app/models/image_like.rb
class ImageLike < ApplicationRecord
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :tweet, counter_cache: :likes_count
    belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    has_many :likes, dependent: :destroy
    def like_user(user_id)
        likes.find_by(user_id: user_id)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :age, presence: true
  has_many :images
  has_many :friendships
  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions

  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
      existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
    end
    existing_chat_users.uniq
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    # @friendships = Friendship.all
    @images = (Image.all - current_user.images).shuffle
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    #check friendship exist?
    friend_id = friendship_params[:friend_id]
    friendship = Friendship.find_by(user_id:friend_id, friend_id:current_user)
    my_friendship = Friendship.find_by(user_id:current_user, friend_id:friend_id)
    if friendship.blank? and my_friendship.blank?
      new_friendship = Friendship.new(user_id: current_user.id, friend_id: friendship_params[:friend_id])
      new_friendship.save
    elsif friendship.present? and friendship.state == "pending"
      friendship.state = "approved"
      friendship.save
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url, notice: 'Friendship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:friend_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/image_likes_helper.rb
module ImageLikesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/friendships/_form.html.erb
<%= simple_form_for(@friendship) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :friend_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<body>
<!-- start padding container -->
<div class="wrap">
  <!-- start jtinder container -->
  <div id="tinderslide">
    <ul>
      <% @images.each do |image| %>
        <li class="pane<%= image.id % 5 + 1 %>" id="user_<%= image.user.id %>">
          <div class="img">
            <% if image.file.present?%>
                <%= image_tag image.file, class:'center-block', style:'align-content: center; background-size: cover; height: 400px;'%>
            <% else %>
                <%= image_tag image.link, class:'center-block', style:'align-content: center; background-size: cover; height: 400px;'%>
            <% end %>
          </div>
          <div style = "color: #ff288d;">
            <%= image.user.name %>
          </div>
          <div style="font-size: 14px">
            <%= image.title %>
          </div>
          <div class="like"></div>
          <div class="dislike"></div>
        </li>
      <% end %>
    </ul>
  </div>
  <!-- end jtinder container -->
</div>
<!-- end padding container -->

<!-- jTinder trigger by buttons  -->
<div class="actions">
  <a href="#" class="dislike"><i></i></a>
  <a href="#" class="like"><i></i></a>
</div>

<!-- jTinder status text  -->
<div id="status"></div>
</body>

<script type="text/javascript">
    $("#tinderslide").jTinder({

        onDislike: function (item) {
            //alert('Dislike image ' + (item.index()+1));
        },
        onLike: function (item) {
            var myId = $("#tinderslide > ul li").last().attr("id").split('_').pop();
            console.log("liked user" + myId);

            $.ajax({
                url: '/friendships',
                type: 'POST',
                data: {
                    friendship: {friend_id: myId}
                },
                success: function (data) {
                    console.log(data);
                    console.log("success");
                },
            });

        },
    });
    $('.actions .like, .actions .dislike').click(function(e){
        e.preventDefault();
        $("#tinderslide").jTinder($(this).attr('class'));
    });
</script>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>