config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  resources :friendships
  resources :images
  devise_for :users
  root 'static_pages#home'

  resources :users do
    resources :chats, only: [:index, :show, :create]
  end
  resources :messages, only:[:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  #if chat is destroyed all messages and subscriptions will also be  destroyed
  has_many :users, through: :subscriptions
  validates :identifier, presence: true, uniqueness: true,    case_sensitive: false
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file ,ImageUploader
  belongs_to :user
  has_many :image_like, -> { order "created_at DESC"}
end

app/models/image_comment.rb
class ImageComment < ActiveRecord::Base
end

app/models/image_like.rb
class ImageLike < ApplicationRecord
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :tweet, counter_cache: :likes_count
    belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    has_many :likes, dependent: :destroy
    def like_user(user_id)
        likes.find_by(user_id: user_id)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :age, presence: true
  has_many :images
  has_many :friendships
  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions

  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
      existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
    end
    existing_chat_users.uniq
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /images
  # GET /images.json
  def index
    @images = current_user.images.reverse

  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:user_id, :title, :file, :created_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/image_likes_helper.rb
module ImageLikesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/images/_form.html.erb
<%= form_for(image, {multipart: true}) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> 画像を保存できませんでした。:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "textIn" %>
  </div>

  <div class="field">
    <%= f.label "画像" %>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent" style="overflow-y: scroll; height:630px;">
    <!-- Tabs Titles -->
    <h2 class="active"> 画像を編集 </h2>

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div>

    <!-- Edit Form -->
    <%= render 'form', image: @image %>

    <%= link_to '表示', @image %> |
    <%= link_to '戻る', images_path %>
  </div>
</div>

app/views/images/index.html.erb
<div class="leading" style=" margin-top: 80px;">
  <p class="leading-bigtext" style="font-size: 80px;"><%= current_user.name %></p>
  <p class="leading-text">愛することによって失うものは何もない。しかし、愛することを怖がっていたら、何も得られない。</p>
</div>
<div style="overflow-y: scroll; height:500px;">

<% @images.each do |image| %>
      <div class="wrapper image-form">
        <div id="formContent">
          <!-- Tabs Titles -->
          <h2 class="active"> <%= image.title %> </h2>

          <!-- Icon -->
          <div class="fadeIn first">
            <% if image.file.present?%>
              <%= link_to (image_tag image.file, class:'center-block', style:'align-content: center; width: 600px;'), image_path(image) %>
            <% else %>
              <%= link_to (image_tag image.link, class:'center-block', style:'align-content: center; width: 600px;'), image_path(image) %>
          <% end %>
          </div>

          <!-- Login Form -->

          <div class="post-bottom">
            <div class="caption">
              <div class="caption-content">
                <%= image.created_at.to_date %>
              </div>
            </div>
          </div>
          <div class="comment-like-form row center-block">
            <%= link_to '表示', image %>
            <%= link_to '編集', edit_image_path(image) %>
            <%= link_to '削除', image, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>

        </div>
      </div>
<% end %>
</div>

app/views/images/new.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent" style="overflow-y: scroll; height:630px;">
    <!-- Tabs Titles -->
    <h2 class="active"> 新しい画像</h2>

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->
    <%= render 'form', image: @image %>

    <%= link_to '戻る', images_path %>
  </div>
</div>

app/views/images/show.html.erb
    <div class="wrapper" style="overflow-y: scroll; height:600px;">
      <div id="formContent2">
        <!-- Tabs Titles -->
        <h2 class="active"> <%=@image.created_at.to_date %></h2>

        <!-- Icon -->
        <div class="fadeIn first">
          <% if @image.file.present?%>
              <%= link_to (image_tag @image.file, class:'center-block', style:'align-content: center; width: 700px;'), image_path(@image) %>
          <% else %>
              <%= link_to (image_tag @image.link, class:'center-block', style:'align-content: center; width: 700px;'), image_path(@image) %>
          <% end %>
        </div>

        <!-- Login Form -->

        <div class="post-bottom">
          <div class="caption">
            <div class="caption-content">
              <%= @image.title %>
            </div>
          </div>
        </div>
        <div class="comment-like-form row center-block">
          <%= link_to '編集', edit_image_path(@image) %> |
          <%= link_to '戻る', images_path %>
        </div>

      </div>
    </div>